### ISSUE TITLE
No longer maintained

### ISSUE THREAD

**Issue by Demond-dev** [kris-nader/sc-type-py#2]
Hi I wanted to know if this package is still maintained? I get a 404 when attempting to access the python script. I wanted to use this to annotate spatial data that has been processed in scanpy.

**Comment by kris-nader** [comment]
Hello,

Yes, we are still maintaining this repo. You can try and use this line:
`url = "https://raw.githubusercontent.com/kris-nader/sc-type-py/main/sctype_py.py"` to fetch the script

Please let me know if this works.
Best,
Kristen
